# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: RearrangeDataset-v0
split: eval
#data_path: data/datasets/single_agent_eval.json.gz
data_path: data/datasets/single_agent_success.json.gz
scenes_dir: "data/scene_datasets/hssd-hab"
