# The rearrangement task with robot_1 perceives the target object first.
# Make sure the robot_0 is spot and the robot_1 is drone.
objects:
  - name: any_targets|0
    expr_type: movable_entity_type
  - name: robot_0
    expr_type: robot_entity_type
  - name: robot_1
    expr_type: robot_entity_type
  - name: robot_2
    expr_type: robot_entity_type
  - name: robot_3
    expr_type: robot_entity_type

goal:
  expr_type: AND
  sub_exprs:
    - robot_at(any_targets|0, robot_0)
    - robot_at(any_targets|0, robot_1)
    - robot_at(any_targets|0, robot_2)
    - robot_at(any_targets|0, robot_3)

stage_goals:
  stage_1:
    expr_type: AND
    sub_exprs:
      - robot_at(any_targets|0, robot_0)
  stage_2:
    expr_type: AND
    sub_exprs:
      - robot_at(any_targets|0, robot_1)
  stage_3:
    expr_type: AND
    sub_exprs:
      - robot_at(any_targets|0, robot_2)
  stage_4:
    expr_type: AND
    sub_exprs:
      - robot_at(any_targets|0, robot_3)

solution:
  - nav_to_goal(any_targets|0, robot_0)
  - nav_to_goal(any_targets|0, robot_1)
  - nav_to_goal(any_targets|0, robot_2)
  - nav_to_goal(any_targets|0, robot_3)
